apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.app_namespace }}  # Set the namespace dynamically
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: nginx:latest
          ports:
            - containerPort: 80
          env:  # Here we define environment variables
            - name: APP_NAMESPACE
              value: {{ .Values.app_namespace }}  # Reference the value from the values file
